import XCTest
@testable import DeuceMateCore

final class WalkthroughSessionTests: XCTestCase {
    private func finish(_ session: inout WalkthroughSession) {
        session.beginExample()
        for _ in 0..<10 where !session.demonstrationFinished {
            session.advanceDemonstration(generation: session.generation)
        }
        XCTAssertTrue(session.demonstrationFinished)
    }
    func testNineSituationsWaitForTapThenRunAutomatically() {
        var s = WalkthroughSession()
        XCTAssertEqual(WalkthroughStep.allCases.count, 9)
        for step in WalkthroughStep.allCases {
            XCTAssertEqual(s.step, step)
            XCTAssertEqual(s.phase, .situation)
            s.advanceDemonstration(generation: s.generation)
            XCTAssertEqual(s.phase, .situation, "Playback cannot start before a tap")
            finish(&s)
            let state = s.state
            let points = s.points
            for _ in 0..<3 { s.advanceDemonstration(generation: s.generation) }
            XCTAssertEqual(s.state, state)
            XCTAssertEqual(s.points, points)
            XCTAssertEqual(s.step, step)
            XCTAssertNil(s.pendingPoint)
            s.next()
        }
        XCTAssertEqual(s.phase, .done)
        XCTAssertEqual(s.step, .oddSet)
        XCTAssertTrue(s.feedback.contains("Track point outcome"))
        s.next()
        XCTAssertEqual(s.phase, .done)
    }
    func testPointGesturesShowExpectedScoresServerAndSide() {
        var win = WalkthroughSession()
        XCTAssertEqual(win.gesture, .win)
        win.beginExample()
        XCTAssertEqual(win.phase, .gesture)
        XCTAssertEqual(win.state.currentPointsMe, 0)
        finish(&win)
        XCTAssertEqual(win.state.currentPointsMe, 1)
        XCTAssertEqual(win.state.currentPointsOpponent, 0)
        XCTAssertEqual(win.state.currentServer, .me)
        XCTAssertFalse(win.isDeuceSide)
        var lose = WalkthroughSession(step: .losePoint)
        XCTAssertEqual(lose.gesture, .lose)
        finish(&lose)
        XCTAssertEqual(lose.state.currentPointsMe, 1)
        XCTAssertEqual(lose.state.currentPointsOpponent, 1)
        XCTAssertEqual(lose.state.currentServer, .me)
        XCTAssertTrue(lose.isDeuceSide)
        var undo = WalkthroughSession(step: .undoPoint)
        XCTAssertEqual(undo.gesture, .undo)
        finish(&undo)
        XCTAssertEqual(undo.state, win.state)
        XCTAssertTrue(undo.points.isEmpty)
    }
    func testAutomaticCategorySequenceRecordsExactlyOneErrorForLosingPlayer() {
        var s = WalkthroughSession(step: .unforcedError)
        s.beginExample()
        s.advanceDemonstration(generation: s.generation)
        XCTAssertEqual(s.phase, .outcome)
        XCTAssertEqual(s.pendingPoint?.server, .me)
        XCTAssertEqual(s.pendingPoint?.winner, .opponent)
        XCTAssertEqual(s.pendingPoint?.gameScoreAtStart, GameScoreSnapshot(server: 0, returner: 0, isTiebreak: false))
        XCTAssertTrue(s.points.isEmpty)
        s.advanceDemonstration(generation: s.generation)
        XCTAssertEqual(s.phase, .endingShot)
        XCTAssertTrue(s.points.isEmpty)
        finish(&s)
        XCTAssertEqual(s.points.count, 1)
        XCTAssertEqual(s.summary.myUnforcedErrors, 1)
        XCTAssertEqual(MatchStatsSummary(stats: s.points, focal: .opponent).myUnforcedErrors, 0)
        XCTAssertEqual(s.points.first?.endingShot, .rally)
        XCTAssertNil(s.points.first?.heartRateBPM)
        XCTAssertNil(s.points.first?.stepsCumulative)
        XCTAssertNil(s.pendingPoint)
        let points = s.points
        s.next()
        XCTAssertEqual(s.step, .secondServe)
        XCTAssertEqual(s.points, points)
        XCTAssertFalse(s.isOnSecondServe)
        finish(&s)
        XCTAssertTrue(s.isOnSecondServe)
        XCTAssertEqual(s.summary.myUnforcedErrors, 1)
    }
    func testGameBoundaryRotatesServerWithBallsOnly() {
        var s = WalkthroughSession(step: .winGame)
        XCTAssertFalse(s.isDeuceSide)
        s.beginExample()
        s.advanceDemonstration(generation: s.generation)
        XCTAssertEqual(s.phase, .changeover)
        XCTAssertEqual(s.state.sets, [SetScore(id: WalkthroughFixtures.setID(0), gamesMe: 2, gamesOpponent: 0)])
        XCTAssertEqual(s.state.currentPointsMe, 0)
        XCTAssertEqual(s.state.currentPointsOpponent, 0)
        XCTAssertEqual(s.state.currentServer, .opponent)
        XCTAssertTrue(s.isDeuceSide)
        XCTAssertEqual(s.changeover?.reason, .evenGames)
        XCTAssertNil(s.reminder)
        finish(&s)
        XCTAssertNil(s.changeover)
        XCTAssertEqual(s.phase, .result)
    }
    func testSecondServeAndDoubleFaultLeadToBothLiveErrorCounts() {
        var serve = WalkthroughSession(step: .secondServe)
        let initial = serve.state
        serve.beginExample()
        XCTAssertEqual(serve.phase, .secondServeTap)
        XCTAssertFalse(serve.isOnSecondServe)
        serve.advanceDemonstration(generation: serve.generation)
        XCTAssertEqual(serve.phase, .result)
        XCTAssertTrue(serve.isOnSecondServe)
        XCTAssertEqual(serve.state, initial, "A double tap must not score a point")
        XCTAssertEqual(serve.recentWinners, [.opponent])

        serve.next()
        XCTAssertEqual(serve.step, .doubleFault)
        XCTAssertTrue(serve.isOnSecondServe)
        serve.beginExample()
        serve.advanceDemonstration(generation: serve.generation)
        XCTAssertEqual(serve.phase, .outcome)
        XCTAssertEqual(serve.pendingPoint?.isSecondServe, true)
        XCTAssertEqual(serve.pendingPoint?.gameScoreAtStart,
                       GameScoreSnapshot(server: 0, returner: 1, isTiebreak: false))
        XCTAssertEqual(serve.state.currentPointsOpponent, 2)
        XCTAssertFalse(serve.isOnSecondServe, "The badge clears after scoring")
        XCTAssertEqual(serve.points.count, 1)
        serve.advanceDemonstration(generation: serve.generation)
        XCTAssertEqual(serve.phase, .result, "Double faults skip ending-shot selection")
        XCTAssertNil(serve.pendingPoint)
        XCTAssertEqual(serve.points.count, 2)
        XCTAssertEqual(serve.points.last?.outcome, .doubleFault)
        XCTAssertEqual(serve.points.last?.endingShot, .serve)
        XCTAssertEqual(serve.points.last?.isSecondServe, true)
        XCTAssertEqual(serve.summary.myUnforcedErrors, 1)
        XCTAssertEqual(serve.summary.myDoubleFaults, 1)
        XCTAssertEqual(serve.recentWinners, [.opponent, .opponent])
        XCTAssertTrue(serve.points.allSatisfy { $0.heartRateBPM == nil && $0.stepsCumulative == nil })

        serve.next()
        XCTAssertEqual(serve.step, .findStat)
        XCTAssertEqual(serve.points, [WalkthroughFixtures.errorPoint, WalkthroughFixtures.doubleFaultPoint])
        XCTAssertEqual(serve.gesture, .stats)
        finish(&serve)
        XCTAssertEqual(serve.phase, .stats)
        XCTAssertEqual(serve.summary.myUnforcedErrors, 1)
        XCTAssertEqual(serve.summary.myDoubleFaults, 1)
    }
    func testTapCannotSkipAnimationAndInterruptedExampleRestartsAtCommentary() {
        var s = WalkthroughSession(step: .doubleFault)
        let startingState = s.state
        let startingPoints = s.points
        s.advanceDemonstration(generation: s.generation)
        XCTAssertEqual(s.phase, .situation)
        s.beginExample()
        XCTAssertEqual(s.phase, .gesture)
        s.beginExample()
        XCTAssertEqual(s.phase, .gesture, "A second tap during playback cannot score")
        s.advanceDemonstration(generation: s.generation)
        XCTAssertEqual(s.phase, .outcome)
        XCTAssertNotNil(s.pendingPoint)
        let interruptedGeneration = s.generation

        s.restartCurrentExample()
        XCTAssertEqual(s.phase, .situation)
        XCTAssertNotEqual(s.generation, interruptedGeneration)
        XCTAssertEqual(s.state, startingState)
        XCTAssertEqual(s.points, startingPoints)
        XCTAssertEqual(s.recentWinners, [.opponent])
        XCTAssertTrue(s.isOnSecondServe)
        XCTAssertNil(s.pendingPoint)
        s.advanceDemonstration(generation: interruptedGeneration)
        XCTAssertEqual(s.phase, .situation)
        finish(&s)
        XCTAssertEqual(s.summary.myDoubleFaults, 1)
    }
    func testSetBoundaryAcknowledgesAutomaticallyThenClearsStickyReminder() {
        var s = WalkthroughSession(step: .oddSet)
        s.beginExample()
        s.advanceDemonstration(generation: s.generation)
        XCTAssertEqual(s.phase, .changeover)
        XCTAssertEqual(s.state.sets, [SetScore(id: WalkthroughFixtures.setID(0), gamesMe: 6, gamesOpponent: 3), SetScore(id: WalkthroughFixtures.setID(1))])
        XCTAssertEqual(s.state.currentServer, .opponent)
        XCTAssertEqual(s.state.currentPointsMe, 0)
        XCTAssertEqual(s.state.currentPointsOpponent, 0)
        XCTAssertTrue(s.isDeuceSide)
        XCTAssertEqual(s.changeover?.reason, .setCompletePlayers)
        XCTAssertEqual(s.reminder, true)
        s.advanceDemonstration(generation: s.generation)
        XCTAssertEqual(s.phase, .postChangeoverScore)
        XCTAssertNil(s.changeover)
        XCTAssertEqual(s.state.currentPointsMe, 0)
        s.advanceDemonstration(generation: s.generation)
        XCTAssertEqual(s.phase, .reminder)
        XCTAssertNil(s.changeover)
        XCTAssertEqual(s.reminder, true)
        s.advanceDemonstration(generation: s.generation)
        XCTAssertEqual(s.phase, .nextSetGesture)
        XCTAssertEqual(s.gesture, .win)
        XCTAssertEqual(s.reminder, true)
        finish(&s)
        XCTAssertNil(s.reminder)
        XCTAssertEqual(s.state.currentServer, .opponent)
        XCTAssertEqual(s.state.currentPointsMe, 1)
        XCTAssertFalse(s.isDeuceSide)
    }
    func testPreviousNextAreAlwaysAvailableAndDiscardStaleAnimationState() {
        var s = WalkthroughSession()
        let first = s.generation
        s.previous()
        XCTAssertEqual(s.generation, first)
        s.next() // Navigation does not require finishing the demonstration.
        XCTAssertEqual(s.step, .losePoint)
        XCTAssertNotEqual(s.generation, first)
        s.advanceDemonstration(generation: first)
        XCTAssertEqual(s.phase, .situation)
        s.previous()
        XCTAssertEqual(s.step, .winPoint)
        XCTAssertEqual(s.state.currentPointsMe, 0)
        for phaseIndex in 0..<6 {
            var set = WalkthroughSession(step: .oddSet)
            set.beginExample()
            for _ in 0..<phaseIndex { set.advanceDemonstration(generation: set.generation) }
            let old = set.generation
            set.previous()
            let expected = WalkthroughSession(step: .winGame)
            set.advanceDemonstration(generation: old)
            XCTAssertEqual(set.state, expected.state)
            XCTAssertEqual(set.phase, .situation)
            XCTAssertNil(set.changeover)
            XCTAssertNil(set.reminder)
            XCTAssertNil(set.pendingPoint)
            XCTAssertTrue(set.points.isEmpty)
        }
        var error = WalkthroughSession(step: .unforcedError)
        error.beginExample()
        error.advanceDemonstration(generation: error.generation)
        XCTAssertNotNil(error.pendingPoint)
        error.next()
        XCTAssertNil(error.pendingPoint)
        finish(&error)
        error.previous()
        XCTAssertEqual(error.step, .unforcedError)
        XCTAssertTrue(error.points.isEmpty)
        XCTAssertEqual(error.phase, .situation)
        var end = WalkthroughSession(step: .oddSet)
        end.next()
        XCTAssertEqual(end.phase, .done)
        end.previous()
        XCTAssertEqual(end.step, .oddSet)
        XCTAssertEqual(end.phase, .situation)
        XCTAssertEqual(end.state, WalkthroughFixtures.state(for: .oddSet))
    }
    func testGestureThresholdsMatchLivePreviewAndStatsBias() {
        XCTAssertEqual(ScoreInputAction.drag(horizontal: 0, vertical: -21), .win)
        XCTAssertEqual(ScoreInputAction.drag(horizontal: 0, vertical: 21), .lose)
        XCTAssertEqual(ScoreInputAction.drag(horizontal: -21, vertical: 0), .undo)
        XCTAssertEqual(ScoreInputAction.drag(horizontal: 41, vertical: 0), .stats)
        XCTAssertNil(ScoreInputAction.drag(horizontal: 0, vertical: -20))
        XCTAssertNil(ScoreInputAction.drag(horizontal: 0, vertical: 20))
        XCTAssertNil(ScoreInputAction.drag(horizontal: -20, vertical: 0))
        XCTAssertNil(ScoreInputAction.drag(horizontal: 40, vertical: 0))
        XCTAssertNil(ScoreInputAction.drag(horizontal: 41, vertical: 21))
        XCTAssertNil(ScoreInputAction.drag(horizontal: 42, vertical: 21))
        XCTAssertEqual(ScoreInputAction.drag(horizontal: 43, vertical: 21), .stats)
        XCTAssertEqual(ScoreInputAction.drag(horizontal: 21, vertical: -21), .win)
        XCTAssertEqual(ScoreInputAction.drag(horizontal: -21, vertical: 21), .lose)
    }
    func testPresenterAdvancesOnlyAfterAutomaticResultThenLoadsFreshFixture() {
        var s = WalkthroughSession(step: .unforcedError)
        let firstGeneration = s.generation
        s.advanceAfterResult()
        XCTAssertEqual(s.phase, .situation)
        XCTAssertTrue(s.points.isEmpty)
        s.finishDemonstration()
        XCTAssertEqual(s.phase, .result)
        XCTAssertEqual(s.points.count, 1)
        XCTAssertEqual(s.recentWinners, [.opponent])
        XCTAssertEqual(s.generation, firstGeneration)
        s.advanceAfterResult()
        XCTAssertEqual(s.step, .secondServe)
        XCTAssertEqual(s.phase, .situation)
        XCTAssertNotEqual(s.generation, firstGeneration)
        XCTAssertEqual(s.recentWinners, [.opponent])
        XCTAssertEqual(s.state, WalkthroughFixtures.state(for: .secondServe))
    }
    func testMomentumFollowsScriptedScoreAndUndo() {
        for step in WalkthroughStep.allCases {
            var s = WalkthroughSession(step: step)
            let initial = WalkthroughFixtures.recentWinners(for: step)
            XCTAssertEqual(s.recentWinners, initial)
            let metrics = WalkthroughFixtures.demoMetrics(for: step)
            XCTAssertGreaterThan(metrics.heartRate, 0)
            XCTAssertGreaterThan(metrics.kilocalories, 0)
            XCTAssertGreaterThan(metrics.elapsedSeconds, 0)
            s.finishDemonstration()
            if step == .undoPoint {
                XCTAssertEqual(s.recentWinners, Array(initial.dropLast()))
            } else if step == .findStat || step == .secondServe {
                XCTAssertEqual(s.recentWinners, initial)
            } else if step == .oddSet {
                XCTAssertEqual(s.recentWinners.suffix(2), [.me, .me])
            } else {
                XCTAssertEqual(s.recentWinners.last, step == .losePoint || step == .unforcedError || step == .doubleFault ? .opponent : .me)
            }
            XCTAssertLessThanOrEqual(s.recentWinners.count, 8)
            XCTAssertTrue(s.points.allSatisfy { $0.heartRateBPM == nil && $0.stepsCumulative == nil })
        }
    }
    func testPresenterWaitsThroughCategoryAndFinalCardIsTerminal() {
        var error = WalkthroughSession(step: .unforcedError)
        error.beginExample()
        error.advanceDemonstration(generation: error.generation)
        XCTAssertEqual(error.phase, .outcome)
        error.advanceAfterResult()
        XCTAssertEqual(error.phase, .outcome)
        XCTAssertNotNil(error.pendingPoint)
        error.finishDemonstration()
        XCTAssertEqual(error.phase, .result)
        XCTAssertNil(error.pendingPoint)
        XCTAssertEqual(error.points.count, 1)
        XCTAssertEqual(error.recentWinners, [.opponent])

        var last = WalkthroughSession(step: .oddSet)
        last.advanceAfterResult()
        XCTAssertEqual(last.phase, .situation)
        last.finishDemonstration()
        XCTAssertEqual(last.phase, .result)
        last.advanceAfterResult()
        XCTAssertEqual(last.phase, .done)
        XCTAssertEqual(last.step, .oddSet)
        last.advanceAfterResult()
        XCTAssertEqual(last.phase, .done)
    }
}
